### ISSUE TITLE
Failure building against 1.0.x IDE

### ISSUE THREAD

**Issue by scottdarch** [scottdarch/Arturo#29]
Arduino didn't use to have "core libraries". Arturo 1.0 currently will fail if these are not found regardless of whether or not they are needed.

**Comment by scottdarch** [comment]
Please take a look @Mausy5043 and @hatchpai. Let me know if patch #30 fixes this for you. If so I'll merge it into master.

**Comment by scottdarch** [comment]
(Note that this bug was opened from a conversation on closed bug #13 )

**Comment by Mausy5043** [comment]
Yes this fixed it for me.

**Comment by hachpai** [comment]
It didn't work for me...

**Comment by Mausy5043** [comment]
Always do `ano clean` before `ano build` !
