### ISSUE TITLE
Uninstall instructions

### ISSUE THREAD

**Issue by Mausy5043** [scottdarch/Arturo#31]
I installed Arturo on my Mac to help debug some issues. I'd like to uninstall it again.
What files are installed? 
Is it just `/usr/local/bin/ano` and `/usr/local/miniterm/py` that need to be removed?

**Comment by scottdarch** [comment]
try this:

```
pip uninstall ano
```

**Comment by Mausy5043** [comment]
:+1: 
I had to `sudo easy_install pip` first. Then `sudo pip uninstall ano` worked.
