### ISSUE TITLE
Doesn't recognize ATmega2560

### ISSUE THREAD

**Issue by armacento** [scottdarch/Arturo#36]
I get this error when trying to upload to the arduino mega: 
```
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00
```
I suspected that ano thought it was an uno board, so I modified `ano/commands/upload.py` to print out the name of the board sent to avrdude: 
```
print BoardModels.getValueForVariant(board, boardVariant, 'build', 'mcu')
```
And it prints out `atmega328p`.  Keep in mind this is after compiling and uploading with 
```
$ ano build --cpu atmega2560
$ ano upload --cpu atmega2560       # I don't know if the flag actually does anything here
```

SOLVED:

After digging through the code I finally found out about the -m argument to specify the model. It now works, but I have to specify both the board and the cpu to compile and upload:
```
$ ano build -m mega --cpu atmega2560
$ ano upload -m mega --cpu atmega2560
```
More comprehensive documentation would probably be all that is necessary, unless an auto-detection system could be implemented in the future.

**Comment by scottdarch** [comment]
You can put these values in an ano.ini at the root of your folder.

As for improvements; when I get Arturo 2.0 out it will handle this sort of stuff much more gracefully.
